AWSTemplateFormatVersion: 2010-09-09
Description: Trend Cloud One All-In-One Onboard Stack

Parameters:
  CloudOneApiKey:
    Description: Cloud One API Key
    Type: String
  CloudOneRegion:
    Description: Cloud One Region
    Type: String
    Default: us-1
    AllowedValues:
       - us-1
       - trend-us-1
       - au-1
       - ie-1
       - sg-1
       - in-1
       - jp-1
       - ca-1
       - de-1
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: cloudone-community
    Description: S3 bucket name for the Quick Start assets. Quick Start bucket name
      can include numbers, lowercase letters, uppercase letters, and hyphens (-).
      It cannot start or end with a hyphen (-).
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/.]*$
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), dots(.) and forward slash (/).
    Default: "latest/"
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), dots(.) and
      forward slash (/).
    Type: String
  
  

Resources:
  WorkloadSecurityIntegrationStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        CloudOneApiKey: !Ref CloudOneApiKey
        CloudOneRegion: !Ref CloudOneRegion
      TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}Common/Cloud-Account/aws-cfn-cloud-account-connector/workloadsecurity.template.yaml'

