AWSTemplateFormatVersion: 2010-09-09
Description: "WS SSM StackSet"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
        Label: 
          default: 'Automation details'
        Parameters:
          - IsDelegatedAdministrator
          - DelegatedAdminAccountId
          - ManagementAccountId
      - 
        Label:
          default: 'Targets'
        Parameters:
          - DeploymentTargets
          - TargetOUs
          - TargetKey
          - TargetValues
          - CronJob
      - 
        Label:
          default: 'Cloud One Workload Security'
        Parameters:
          - dsActivationUrl
          - dsManagerUrl
          - dsTenantId
          - dsToken
Parameters:
  IsDelegatedAdministrator:
    Type: String
    AllowedValues:
    - 'true'
    - 'false'
    Description: Specify if this solution is being deployed in a delegated adminstrator account. With this option you no longer need to be logged into the AWS Organizations management account to administer software package distribution.
  DeploymentTargets:
    Description: Specify AWS Organizational Unit IDs within AWS Organization whose accounts have the target instances (ou-name) for distribution. (Account IDs are only allowed when updating)
    Type: CommaDelimitedList
    Default: ''
  TargetKey:
    Type: String
    Description: Specify which instances have to be targeted for this solution. Allowed values - ParameterValues, ResourceGroup or begin with tag:, AWS::EC2::Instance, InstanceIds (default), instanceids. Refer https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_Target.html for more details.
    Default: 'InstanceIds'
  TargetValues:
    Type: String
    Description: Specify the values of the target keys specified above. Default is *, which targets all instances. Refer https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_Target.html for more details.
    Default: '*'
  ManagementAccountId:
    Description: (Required) AWS Organization's Management account ID.
    Type: String
    Default: ''
  DelegatedAdminAccountId:
    Description: (Optional) Delegated administrator account ID.
    Type: String
    Default: ''
  CronJob:
    Type: String
    Description: Specify the CRON Job for future scheduling. [Default is everyday @10:15AM - cron(15 10 * * ? *)]
    Default: 'cron(15 10 * * ? *)'
  dsActivationUrl:
    Type: String
    Description: "Cloud One Workload Security Activation URL."
    NoEcho: true
    Default: ''
  dsManagerUrl:
    Type: String
    Description: "Cloud One Workload Security Manager URL."
    NoEcho: true
    Default: ''
  dsTenantId:
    Type: String
    Description: "Cloud One Workload Security Tenant ID."
    NoEcho: true
    Default: ''
  dsToken:
    Type: String
    Description: "Cloud One Workload Security Token ID."
    NoEcho: true
    Default: ''
  
Conditions:
  IsDelegatedAdministrator: 
    !Equals [!Ref IsDelegatedAdministrator,'true']
Resources:
  SSMStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties: 
      AutoDeployment:
          Enabled: true
          RetainStacksOnAccountRemoval: false
      CallAs: !If [IsDelegatedAdministrator,DELEGATED_ADMIN,SELF]
      Capabilities:
          - CAPABILITY_AUTO_EXPAND
          - CAPABILITY_IAM
          - CAPABILITY_NAMED_IAM
      Description: SSM Stackset for C1WS
      Parameters: 
        - 
          ParameterKey: dsActivationUrl
          ParameterValue: !Ref dsActivationUrl
        - 
          ParameterKey: dsManagerUrl
          ParameterValue: !Ref dsManagerUrl
        - 
          ParameterKey: dsTenantId
          ParameterValue: !Ref dsTenantId
        - 
          ParameterKey: dsToken
          ParameterValue: !Ref dsToken
        - 
          ParameterKey: TargetKey
          ParameterValue: !Ref TargetKey
        - 
          ParameterKey: TargetValues
          ParameterValue: !Ref TargetValues
        - 
          ParameterKey: CronJob
          ParameterValue: !Ref CronJob
      PermissionModel: SERVICE_MANAGED
      StackInstancesGroup:
          - Regions:
            - us-east-1
            - us-east-2
            - us-west-1
            - us-west-2
            - ap-south-1
            - ap-northeast-3
            - ap-northeast-2
            - ap-southeast-1
            - ap-southeast-2
            - ca-central-1
            - eu-central-1
            - eu-west-1
            - eu-west-2
            - eu-west-3
            - eu-north-1
            - sa-east-1
            DeploymentTargets:
              OrganizationalUnitIds: !Ref DeploymentTargets
      StackSetName: C1WS-SSM-StackSet
      TemplateBody: |
        Parameters:
          dsActivationUrl:
            Type: String
            Description: "Cloud One Workload Security Activation URL."
            NoEcho: true
          dsManagerUrl:
            Type: String
            Description: "Cloud One Workload Security Manager URL."
            NoEcho: true
          dsTenantId:
            Type: String
            Description: "Cloud One Workload Security Tenant ID."
            NoEcho: true
          dsToken:
            Type: String
            Description: "Cloud One Workload Security Token ID."
            NoEcho: true
          TargetKey:
            Type: String
            Description: Specify which instances have to be targeted for this solution. Allowed values - ParameterValues, ResourceGroup or begin with tag:, AWS::EC2::Instance, InstanceIds (default), instanceids. Refer https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_Target.html for more details.
            Default: 'InstanceIds'
          TargetValues:
            Type: String
            Description: Specify the values of the target keys specified above. Default is *, which targets all instances. Refer https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_Target.html for more details.
            Default: '*'
          CronJob:
            Type: String
            Description: Specify the CRON Job for future scheduling. [Default is everyday @10:15AM - cron(15 10 * * ? *)]
            Default: 'cron(15 10 * * ? *)'
        Resources:
          DSActivationUrlParam:
            Type: "AWS::SSM::Parameter"
            Properties:
              Name: "dsActivationUrl"
              Type: "String"
              Value: !Ref dsActivationUrl
              Description: "Cloud One Workload Security Activation URL"
              Tags:
                Key: CloudOne
                Value: WS-SSM
          DSManagerUrlParam:
            Type: "AWS::SSM::Parameter"
            Properties:
              Name: "dsManagerUrl"
              Type: "String"
              Value: !Ref dsManagerUrl
              Description: "Cloud One Workload Security Manager URL"
              Tags:
                Key: CloudOne
                Value: WS-SSM
          DSTenantIdParam:
            Type: "AWS::SSM::Parameter"
            Properties:
              Name: "dsTenantId"
              Type: "String"
              Value: !Ref dsTenantId
              Description: "Cloud One Workload Security Tenant ID"
              Tags:
                Key: CloudOne
                Value: WS-SSM
          DSTokenParam:
            Type: "AWS::SSM::Parameter"
            Properties:
              Name: "dsToken"
              Type: "String"
              Value: !Ref dsToken
              Description: "Cloud One Workload Security Token ID"
              Tags:
                Key: CloudOne
                Value: WS-SSM
          C1WSDistributorPackage:
            Type: AWS::SSM::Association
            Properties:
              AssociationName: TrendCloudOneWorkloadSecurityAssociation
              Name: AWS-ConfigureAWSPackage
              ScheduleExpression: !Ref CronJob
              Parameters: 
                action:
                  - Install
                installationType:
                  - In-place update
                name:
                  - TrendMicro-CloudOne-WorkloadSecurity
              Targets: 
                - Key: !Ref TargetKey
                  Values:
                  - !Ref TargetValues

