Parameters:
    Region:
      Type: String
      Description: Please enter the region in which the lambda will be executed
    s3Bucket:
      Type: String
      Description: Enter the name of the s3 bucket where you upload the Lambda Layer and package
    ApiKey:
      Type: String
      Description: Please enter your Deep Security API Key
    EmailSender:
      Type: String
      Description: Email id to be used for sending report
    EmailRecipients:
      Type: String
      Description: Comma separated email ids for recieving report
    WorkloadSecurityHost:
      Type: String
      Description: Enter your Workload Security Host 
      Default: https://workload.trend-us-1.cloudone.trendmicro.com/api
    CronSchedule:
      Type: String
      Description: Enter the when you would like the lambda function to run in the cron format

Resources:
  LambdaLayer2:
    Type: "AWS::Lambda::LayerVersion"
    Properties:
      CompatibleRuntimes:
        - python3.9
      Content:
        S3Bucket: !Ref s3Bucket
        S3Key: "python.zip"
      LayerName: "DSlayer"
  
  LambdaRoleForRuleAssignment: 
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              Service: 
                - "lambda.amazonaws.com" 
            Action: 
              - "sts:AssumeRole"  
      ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AmazonVPCCrossAccountNetworkInterfaceOperations
          # - !Ref ManagedPolicyforlambda 
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
          - arn:aws:iam::aws:policy/AmazonInspector2ReadOnlyAccess
          - arn:aws:iam::aws:policy/AmazonSESFullAccess

  LambdaLayerParameterForAutoAssignment:
    Type: AWS::SSM::Parameter
    Properties:
      Name: lambda_layer_for_auto_assign_ips_rule
      Type: String
      Value: "NA"

  LambdaFunctionForAutoAssignment:
    Type: "AWS::Lambda::Function"
    DependsOn:
      - "LambdaLayerParameterForAutoAssignment"
    Properties:
      Environment:
        Variables:
          region: !Ref Region
          apikey: !Ref ApiKey
          sender: !Ref EmailSender
          recipients: !Ref EmailRecipients
          host: !Ref WorkloadSecurityHost
      Code:
        S3Bucket: !Ref s3Bucket
        S3Key: "auto-assign-lambda.py.zip"
      FunctionName: "LambdaFunctionForAutoAssignment"
      Handler: "auto-assign-lambda.lambda_handler"
      Layers:
        - !Ref LambdaLayer2
      Runtime: python3.9
      Timeout: 300
      Role: !GetAtt LambdaRoleForRuleAssignment.Arn
  ScheduledRule: 
    Type: AWS::Events::Rule
    Properties: 
      Description: "ScheduledRule"
      ScheduleExpression: !Sub ${CronSchedule} 
      State: "ENABLED"
      Targets: 
        - 
          Arn: 
            Fn::GetAtt: 
              - "LambdaFunctionForAutoAssignment"
              - "Arn"
          Id: "TargetFunctionV1"
  PermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !Ref "LambdaFunctionForAutoAssignment"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - "ScheduledRule"
          - "Arn"