name: Bash-Linter

# It trigger when any push or PR is made in the the code under the main branch
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

# Linter to check errors in the bash script
jobs:
   Bash-Linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck Action
        uses: ludeeus/action-shellcheck@master
        with:
          severity: error
          format: tty
