name: Sync to S3

env:
  BUCKET_NAME: 'cloudone-community'
  AWS_REGION: 'us-east-1'

on:
  push:
    branches:
    - main
  
# Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git/*'
      env:
        AWS_S3_BUCKET: ${{ env.BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ env.AWS_REGION }}
        DEST_DIR: latest